### ISSUE TITLE
Add Avatars

### ISSUE THREAD

**Issue by namitoyokota** [namitoyokota/KeepInTouch#20]

**Comment by namitoyokota** [comment]
When creating/editing a friend, the user can assign an avatar to go within the card!!! SUPER EXCITING LOOK

https://www.iconfinder.com/search/3d-illustrations?family=3d-avatars

**Comment by namitoyokota** [comment]
Also maybe even pick colors for them to show up in the card background!

**Comment by namitoyokota** [comment]
Create custom context menu maybe for selecting them

https://stackoverflow.com/questions/45221435/custom-context-menu-in-angular#45223286

**Comment by namitoyokota** [comment]
Download Avatars folder from iCloud Drive

**Comment by namitoyokota** [comment]
Create a new component: `select-avatar`

**Comment by namitoyokota** [comment]
friend.ts
```typescript
/** Assigned identifier for the avatar image */
avatarId?: string;
```

**Comment by namitoyokota** [comment]
select-avatar.component.ts
```typescript
/** Currently selected avatar */
@Input() selectedAvatar: string;

/** Emits when avatar has been selected */
@Output() avatarChanged = new EventEmitter<string>();

/** List of avatars to select from */
readonly avatarList: string[] = [];

/** Flag to indicate when avatar list is open */
isSelectingAvatar = false;
```

```typescript
selectAvatar(avatarId: string): void {
  this.avatarChanged.emit(avatarId);
}

private retrieveAvatars(): void {
  // Gets filenames of the avatar icons and sets to avatarList
}
```

**Comment by namitoyokota** [comment]
select-avatar.component.html
```html
<!— Open List Button —>
<button nbButton (click)=“showList()”>Select Avatar</button>

<!— Avatar List —>
<div *ngIf=“isSelectingAvatar” class=“avatar-list”>
  <div *ngFor=“let avatarId of avatarList” class=“avatar”>
    <img src=“${avatarId}.png” (click)=“selectAvatar(avatarId)” />
  </div>
</div>
```

**Comment by namitoyokota** [comment]
select-avatar.component.scss
```scss
:host {
  display: grid;
  grid-template-rows: min-content auto;
  row-gap: 10px;
}

.avatar-list {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  column-gap: 10px;
  border: 2px solid black;
  border-radius: 5px;

  .avatar {
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid black;
    border-radius: 5px;
  }
}
```
